# Generated by Django 5.2.7 on 2026-04-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('ransomware', 'Ransomware'), ('phishing', 'Phishing'), ('ddos', 'DDoS Attack'), ('sql_injection', 'SQL Injection'), ('mitm', 'Man-in-the-Middle'), ('zero_day', 'Zero-Day Exploit'), ('insider_threat', 'Insider Threat'), ('brute_force', 'Brute Force')], max_length=50)),
                ('detection_delay', models.FloatField(help_text='Detection delay in minutes')),
                ('server_load', models.FloatField(help_text='Server load at time of attack (0–100%)')),
                ('patch_status', models.CharField(choices=[('patched', 'Fully Patched'), ('partial', 'Partially Patched'), ('unpatched', 'Unpatched')], max_length=20)),
                ('firewall_status', models.CharField(choices=[('strong', 'Strong (Next-Gen Firewall)'), ('moderate', 'Moderate (Standard Firewall)'), ('weak', 'Weak (Basic/Outdated)'), ('none', 'No Firewall')], max_length=20)),
                ('affected_systems', models.IntegerField(help_text='Number of systems affected')),
                ('data_sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('top_secret', 'Top Secret')], default='internal', max_length=20)),
                ('attack_vector', models.CharField(choices=[('external', 'External'), ('internal', 'Internal'), ('supply_chain', 'Supply Chain')], default='external', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('damage_score', models.FloatField(blank=True, null=True)),
                ('counterfactual_damage', models.FloatField(blank=True, null=True)),
                ('counterfactual_delay', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20)),
                ('damage_saved', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
